# -*- coding: utf-8 -*-
"""ExercicioValidacaoEmail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WvpZkU0VqljIFNnD8NBuG2g31ISqw6iX
"""

# https://docs.python.org/3/library/re.html

import re

def validar_email(email):
    # Expressão regular para validar o e-mail
    padrao = r'^[a-zA-Z0-9]+[\w._]*@[a-zA-Z]+\.(com|edu|org)(\.br)?$'
    # Verifica se o e-mail corresponde ao padrão
    if re.match(padrao, email):
        return True
    else:
        return False

def main():
    # Solicita ao usuário que digite o e-mail
    email = input("Digite o e-mail: ")
    # Verifica se o e-mail é válido
    if validar_email(email):
        print("E-mail válido!")
    else:
        print("E-mail inválido!")

if __name__ == "__main__":
    main()