# -*- coding: utf-8 -*-
"""ExercicioPalindromoRegexipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-hMkXfT4hx01XhZ-0FprBJ4wNrxcqI-
"""

import re

def remover_nao_alfanumericos(texto):
    # Substitui todos os caracteres não alfanuméricos por uma string vazia
    return re.sub(r'[^a-zA-Z0-9]', '', texto)

def e_palindromo(texto):
    texto_limpo = remover_nao_alfanumericos(texto.lower())  # Convertendo para minúsculas e removendo caracteres não alfanuméricos
    return texto_limpo == texto_limpo[::-1]  # Verifica se a string é igual à sua versão invertida


# Exemplo de uso
string1 = "socorram-me subi no onibus em marrocos"
string2 = "python"
string3 = "A man, a plan, a canal, Panama!"

print(e_palindromo(string1))
print(e_palindromo(string2))
print(e_palindromo(string3))